# Generated by Django 5.0.2 on 2024-02-17 14:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0003_alter_partner_early_partner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'партнер', 'verbose_name_plural': 'партнеры'},
        ),
        migrations.RemoveField(
            model_name='partner',
            name='backlog',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='date_create',
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backlog', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='задолженность')),
                ('date_create', models.DateField(default=django.utils.timezone.now, verbose_name='время создания')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chain.partner')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщики',
                'ordering': ('-partner',),
            },
        ),
    ]
