# Generated by Django 5.0.2 on 2024-02-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0004_alter_partner_options_remove_partner_backlog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suppliers',
            options={'ordering': ('-date_create',), 'verbose_name': 'поставщик', 'verbose_name_plural': 'поставщики'},
        ),
    ]
