# Generated by Django 5.0.2 on 2024-02-17 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0005_alter_suppliers_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='early_partner',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='partner',
        ),
        migrations.AddField(
            model_name='suppliers',
            name='suppliers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chain.partner', verbose_name='поставщик предыдущий'),
        ),
    ]
