# Generated by Django 5.0.2 on 2024-02-17 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0007_partner_early_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='backlog',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='задолженность'),
        ),
        migrations.AddField(
            model_name='partner',
            name='date_create',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='время создания'),
        ),
        migrations.DeleteModel(
            name='Suppliers',
        ),
    ]
