# Generated by Django 5.0.2 on 2024-02-17 15:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0008_partner_backlog_partner_date_create_delete_suppliers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время создания'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='early_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chain.partner', verbose_name='поставщик предыдущий'),
        ),
    ]
