# Generated by Django 5.0.2 on 2024-02-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0010_alter_partner_early_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='product',
        ),
    ]
