# Generated by Django 5.0.2 on 2024-02-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0011_remove_partner_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='product',
            field=models.ManyToManyField(to='chain.product', verbose_name='продукт'),
        ),
    ]
