# Generated by Django 5.0.2 on 2024-02-17 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0012_partner_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='страна')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='город')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='улица')),
                ('house_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='номер дома')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакты',
            },
        ),
        migrations.RemoveField(
            model_name='partner',
            name='city',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='country',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='street',
        ),
        migrations.AlterField(
            model_name='partner',
            name='product',
            field=models.ManyToManyField(to='chain.product', verbose_name='продукты'),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chain.contact', verbose_name='контакты'),
        ),
    ]
