# Generated by Django 5.0.2 on 2024-02-17 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0014_remove_partner_contact_contact_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='early_partner',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='title',
        ),
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chain.partner', verbose_name='контакты'),
        ),
    ]
