# Generated by Django 5.0.2 on 2024-02-17 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0016_remove_contact_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='early_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chain.contact', verbose_name='поставщик предыдущий'),
        ),
    ]
