# Generated by Django 5.0.2 on 2024-02-17 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0017_partner_early_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='partners',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chain.partner', verbose_name='контакты'),
        ),
    ]
