# Generated by Django 5.0.2 on 2024-02-17 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0018_contact_partners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='partners',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='early_partner',
        ),
        migrations.AddField(
            model_name='partner',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chain.contact', verbose_name='контакты'),
        ),
    ]
