# Generated by Django 5.0.2 on 2024-02-18 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0020_remove_partner_contact_contact_partners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='partners',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='title',
        ),
        migrations.AddField(
            model_name='partner',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chain.contact', verbose_name='контакты'),
        ),
        migrations.AddField(
            model_name='partner',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='название'),
        ),
    ]
