# Generated by Django 5.0.2 on 2024-02-18 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0021_remove_contact_partners_remove_contact_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='early_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chain.partner', verbose_name='поставщик предыдущий'),
        ),
    ]
