# Generated by Django 5.0.2 on 2024-02-18 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0022_partner_early_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chain.partner'),
        ),
    ]
