# Generated by Django 5.0.2 on 2024-02-18 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0023_remove_partner_contact_contact_partner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'поставщик', 'verbose_name_plural': 'поставщики'},
        ),
    ]
